echo "We are trying this practical from linux EC2"
echo "I am from Young minds"
echo "We are from batch-27 and learning DevOps"
echo "Hello, Good morning!"
echo "we are learning Git hub"
echo "we are learning AZURE"
echo "we are learning DevOps"
echo "we are learning Linux"
echo "we are learning AWS"
